name: Run Google Colab Notebook

# Trigger the workflow every 30 minutes
on:
  schedule:
    - cron: '*/01 * * * *'  # Runs every 30 minutes

jobs:
  run-colab:
    runs-on: ubuntu-latest  # Use the latest version of Ubuntu

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # Checks out your repository

    - name: Install colab-cli
      run: pip install colab-cli  # Install colab-cli to trigger Colab notebooks

    - name: Run Colab Notebook
      run: |
        colab-cli run --path path/to/your_notebook.ipynb  # Replace with the correct path to your .ipynb file
