name: Run Colab Notebook Manually on Node.js 20

on:
  workflow_dispatch:

jobs:
  run-colab:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js 20
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install colab-cli
      run: |
        pip install colab-cli

    - name: Run Google Colab Notebook
      run: |
        colab-cli start --path https://colab.research.google.com/drive/1qbxBtj9oRab0QSOaxmbLxFzRYgI4cGmb
