name: Run Google Colab Notebook

on:
  schedule:
    - cron: '*/1 * * * *'  # Runs every minute

jobs:
  run-colab:
    runs-on: ubuntu-latest  # Use the latest version of Ubuntu

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # Checkout your repository

    - name: Install colab-cli
      run: pip install colab-cli  # Install colab-cli to interact with Google Colab

    - name: Run Colab Notebook
      run: |
        colab-cli run --path https://github.com/sauravJ14/Auto-Colab-runner/blob/main/random_num_generator.ipynb  # Link to your Colab notebook in GitHub
