name: Run Google Colab Notebook Manually

on:
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  run-colab:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    # Install Git
    - name: Install Git
      run: |
        sudo apt-get update
        sudo apt-get install -y git

    # Install colab-cli and gitpython
    - name: Install colab-cli and gitpython
      run: |
        pip install gitpython
        pip install colab-cli

    # Check available colab-cli commands
    - name: Check colab-cli commands
      run: |
        colab-cli --help
