name: Run Google Colab Notebook Manually

on:
  workflow_dispatch:  # This allows you to trigger the workflow manually

jobs:
  run-colab:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    # Install Git
    - name: Install Git
      run: |
        sudo apt-get update
        sudo apt-get install -y git

    # Install colab-cli
    - name: Install colab-cli
      run: |
        pip install colab-cli

    # Run the Google Colab Notebook
    - name: Run Google Colab Notebook
      run: |
        colab-cli start --path https://colab.research.google.com/drive/1qbxBtj9oRab0QSOaxmbLxFzRYgI4cGmb
