name: Run Google Colab Notebook

on:
  schedule:
    - cron: '*/1 * * * *'  # Runs every minute
  workflow_dispatch:  # Allows manual triggering

jobs:
  run-colab:
    runs-on: ubuntu-latest  # Use the latest version of Ubuntu

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # Checks out your repository

    - name: Install colab-cli and gitpython
      run: |
        pip install colab-cli  # Install colab-cli
        pip install gitpython  # Install gitpython (required by colab-cli)

    - name: Run Colab Notebook
      run: |
        colab-cli run --path https://github.com/sauravJ14/Auto-Colab-runner/blob/main/random_num_generator.ipynb
